---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenxiao.
--- DateTime: 2022/6/20 20:15
---



local tbl = {}

table.insert(tbl,  1)
table.insert(tbl,  2)
print(table.unpack(tbl))

--for k,v in pairs(tbl) do
--    print(k,v)
--end


